# good practice to enable these rules - I disabled them to avoid seeing warnings
disabled_rules:
- file_length # detect files that should probably be broken up
- force_try # forced tries should be avoided!!!
- identifier_name # use standard naming convention
- line_length # avoid too long lines
- todo # TODO's should be done :)
- type_body_length

opt_in_rules:
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- collection_alignment
- contains_over_filter_count
- contains_over_filter_is_empty
- empty_count
- first_where
- identical_operands
- implicit_return
- joined_default_parameter
- last_where
- redundant_type_annotation
- sorted_first_last
- sorted_imports
- toggle_bool
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
